version: '3.8'

services:
  opensource-linktree:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensource-linktree-app
    ports:
      - "8083:80"
    restart: unless-stopped
